FROM golang:1.21.5 AS build-stage

# COPY go.mod go.sum ./
# RUN go mod download
WORKDIR /app

COPY hello.go /app/hello.go


RUN GOOS=linux CGO_ENABLED=0 go build -o /app/hello hello.go

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/hello /hello

CMD ["/hello"]