apiVersion: v1
kind: Service
metadata:
  namespace: bankapp
  labels:
    role: db
  name: database
spec:
 type: ClusterIP
 ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
 selector:
   app: mysql-db