apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: git@github.com:moazrefat/bankapp.git
      sshPrivateKeySecret:
        name: argocd-ssh-keypair
        key: core-ci
  timeout.reconciliation: 60s